### ISSUE TITLE
Question: how do I run this?

### ISSUE THREAD

**Issue by tomer-ben-david** [weiji14/atom-hydrogen#1]
Does it actually open atom UI with hydrogen?  I tried to build and run this but nothing comes up on screen:

```
docker build -t tomer/hydrogen .
docker run -it tomer/hydrogen
```
nothing comes up on screen... thanks..

**Comment by weiji14** [comment]
Sorry for noticing this so late... You've probably resolved this already but just in case anyone else needs the answer, I'll put it down here.

Basically you'll need to set up X11 and ALSA forwarding so that the GUI comes up. I've documented the procedure at https://github.com/weiji14/cryospheric-data-lakes/tree/master/code/docker#atom so you'll need to do something like this:

```
docker run --rm -p 8888:8888 -v /tmp/.X11-unix/:/tmp/.X11-unix/ -v /dev/shm:/dev/shm -v `dirname "$PWD"`:/home/atom -e DISPLAY tomer/hydrogen
```

I'm gonna close this issue (feel free to reopen if necessary) as the Dockerfile here hasn't been updated for a while. This was written back when atom-beta was quite new and hard to install. There is actually a much easier way now to install atom-beta in a Dockerfile using a debian package.
